-- Catálogo MAESTRO GLOBAL de insumos (sin bodega) — tablas del documento de
-- observaciones de carga inicial. La UI lo usa para autocompletar; cada bodega
-- crea su copia editable en insumo_catalogo al elegir un producto.
-- Idempotente: ON CONFLICT (ambito, categoria, nombre_comercial) DO NOTHING.
--   npm run seed:insumos-maestro   (no requiere bodega)

-- ══════════════════════════ FINCA ══════════════════════════
INSERT INTO "insumo_maestro"
  ("ambito","categoria","familia","principio_activo","nombre_comercial","unidad","dosis_min","dosis_max","unidad_dosis")
SELECT 'finca'::"AmbitoInsumo", v.cat, v.fam, v.pa, v.nom, v.uni, v.dmin::numeric, v.dmax::numeric, v.ud
FROM (VALUES
  -- 1. Fertilizantes Inorgánicos
  ('Fertilizantes Inorgánicos','Nitrogenado','Urea','Urea Perlada','kg',100,250,'kg/ha'),
  ('Fertilizantes Inorgánicos','Nitrogenado','Nitrato de Amonio','Nitrocomplex','kg',150,300,'kg/ha'),
  ('Fertilizantes Inorgánicos','Nitrogenado','Sulfato de Amonio','Sulfato de Amonio','kg',150,250,'kg/ha'),
  ('Fertilizantes Inorgánicos','Fosfatado','MAP','MAP Profertil','kg',80,200,'kg/ha'),
  ('Fertilizantes Inorgánicos','Fosfatado','DAP','DAP Profertil','kg',100,250,'kg/ha'),
  ('Fertilizantes Inorgánicos','Fosfatado','Superfosfato Triple','SPT','kg',120,300,'kg/ha'),
  ('Fertilizantes Inorgánicos','Potásico','Cloruro de Potasio','MOP','kg',80,200,'kg/ha'),
  ('Fertilizantes Inorgánicos','Potásico','Sulfato de Potasio','K-Plus','kg',80,180,'kg/ha'),
  ('Fertilizantes Inorgánicos','Potásico','Nitrato de Potasio','Multi-K','kg',50,150,'kg/ha'),
  ('Fertilizantes Inorgánicos','Corrector','Sulfato de Magnesio','Kieserita','kg',50,120,'kg/ha'),
  ('Fertilizantes Inorgánicos','Micronutriente','Sulfato de Zinc','Zinc Sulfato','kg',5,20,'kg/ha'),
  ('Fertilizantes Inorgánicos','Micronutriente','Sulfato de Manganeso','Manganeso Sulfato','kg',5,20,'kg/ha'),
  ('Fertilizantes Inorgánicos','Corrector','Nitrato de Calcio','YaraLiva','kg',100,250,'kg/ha'),
  ('Fertilizantes Inorgánicos','Fertirriego','Ácido Fosfórico','Phos Acid','L',10,40,'L/ha'),
  ('Fertilizantes Inorgánicos','Fertirriego','Nitrato de Magnesio','Magnisal','kg',25,100,'kg/ha'),
  -- 2. Fertilizantes Orgánicos
  ('Fertilizantes Orgánicos','Compost','Compost Orgánico','Compost','tn',5,20,'tn/ha'),
  ('Fertilizantes Orgánicos','Humus','Humus de Lombriz','Humus','kg',500,2000,'kg/ha'),
  ('Fertilizantes Orgánicos','Guano','Guano de Ave','Guano Pelletizado','kg',300,1000,'kg/ha'),
  ('Fertilizantes Orgánicos','Estiércol','Estiércol Bovino Compostado','Compost Bovino','tn',10,30,'tn/ha'),
  ('Fertilizantes Orgánicos','Estiércol','Estiércol Equino Compostado','Compost Equino','tn',10,30,'tn/ha'),
  ('Fertilizantes Orgánicos','Ácidos Húmicos','Ácidos Húmicos','Humiplex','L',10,30,'L/ha'),
  ('Fertilizantes Orgánicos','Ácidos Fúlvicos','Ácidos Fúlvicos','Fulvimax','L',5,20,'L/ha'),
  ('Fertilizantes Orgánicos','Bioestimulante','Extracto de Algas','Kelpak','L',2,6,'L/ha'),
  ('Fertilizantes Orgánicos','Aminoácidos','Aminoácidos','Terra-Sorb','L',2,5,'L/ha'),
  ('Fertilizantes Orgánicos','Biofertilizante','Biofertilizante Líquido','Biofert','L',10,50,'L/ha'),
  -- 3. Insecticidas
  ('Insecticidas','Neonicotinoide','Imidacloprid','Confidor','L',0.15,0.40,'L/ha'),
  ('Insecticidas','Neonicotinoide','Acetamiprid','Mospilan','kg',0.10,0.25,'kg/ha'),
  ('Insecticidas','Neonicotinoide','Thiamethoxam','Actara','kg',0.10,0.30,'kg/ha'),
  ('Insecticidas','Piretroide','Lambda-Cialotrina','Karate Zeon','L',0.10,0.25,'L/ha'),
  ('Insecticidas','Piretroide','Cipermetrina','Cipermetrina','L',0.15,0.30,'L/ha'),
  ('Insecticidas','Piretroide','Deltametrina','Decis','L',0.10,0.20,'L/ha'),
  ('Insecticidas','Avermectina','Abamectina','Vertimec','L',0.20,0.50,'L/ha'),
  ('Insecticidas','Espinosinas','Spinosad','Success','L',0.10,0.30,'L/ha'),
  ('Insecticidas','Regulador','Lufenurón','Match','L',0.15,0.30,'L/ha'),
  ('Insecticidas','Biológico','Azadiractina','NeemAzal','L',1,3,'L/ha'),
  -- 4. Fungicidas
  ('Fungicidas','Inorgánico','Azufre','Azufre Micronizado','kg',3,8,'kg/ha'),
  ('Fungicidas','Cúprico','Oxicloruro de Cobre','Cobre Nordox','kg',2,5,'kg/ha'),
  ('Fungicidas','Cúprico','Hidróxido de Cobre','Kocide','kg',2,4,'kg/ha'),
  ('Fungicidas','Sistémico','Fosetil-Al','Aliette','kg',2,4,'kg/ha'),
  ('Fungicidas','Sistémico','Metalaxil-M','Ridomil Gold','kg',2,3,'kg/ha'),
  ('Fungicidas','Protectante','Mancozeb','Dithane','kg',2,4,'kg/ha'),
  ('Fungicidas','Protectante','Captan','Captan 80','kg',2,4,'kg/ha'),
  ('Fungicidas','Estrobilurina','Azoxystrobin','Amistar','L',0.5,1,'L/ha'),
  ('Fungicidas','Estrobilurina','Pyraclostrobin','Cabrio Top','kg',1,2,'kg/ha'),
  ('Fungicidas','Triazol','Tebuconazole','Folicur','L',0.4,1,'L/ha'),
  ('Fungicidas','Triazol','Penconazole','Topas','L',0.2,0.5,'L/ha'),
  ('Fungicidas','Triazol','Myclobutanil','Systhane','L',0.2,0.5,'L/ha'),
  -- 5. Herbicidas
  ('Herbicidas','Sistémico','Glifosato','Roundup','L',2,5,'L/ha'),
  ('Herbicidas','Contacto','Glufosinato de Amonio','Finale','L',2,4,'L/ha'),
  ('Herbicidas','Residual','Oxyfluorfen','Goal','L',0.5,1.5,'L/ha'),
  ('Herbicidas','Residual','Pendimetalin','Herbadox','L',2,4,'L/ha'),
  ('Herbicidas','Residual','Simazina','Gesatop','kg',2,5,'kg/ha'),
  ('Herbicidas','Residual','Diuron','Karmex','kg',2,4,'kg/ha'),
  ('Herbicidas','Residual','Flumioxazin','Pledge','kg',0.08,0.15,'kg/ha'),
  ('Herbicidas','Contacto','Carfentrazone-Ethyl','Shark','L',0.05,0.10,'L/ha'),
  ('Herbicidas','Contacto','Saflufenacil','Heat','kg',0.03,0.07,'kg/ha'),
  ('Herbicidas','Sulfonilurea','Flazasulfuron','Chikara','kg',0.15,0.20,'kg/ha'),
  -- 6. Coadyuvantes
  ('Coadyuvantes','Tensioactivo',NULL,'No Iónico','L',NULL,NULL,NULL),
  ('Coadyuvantes','Aceite',NULL,'Aceite Mineral','L',NULL,NULL,NULL),
  ('Coadyuvantes','Aceite',NULL,'Aceite Vegetal','L',NULL,NULL,NULL),
  ('Coadyuvantes','Acidificante',NULL,'Corrector de pH','L',NULL,NULL,NULL),
  ('Coadyuvantes','Antiespumante',NULL,'Antiespumante','L',NULL,NULL,NULL),
  ('Coadyuvantes','Adherente',NULL,'Adherente','L',NULL,NULL,NULL),
  -- 7. Semillas
  ('Semillas','Gramíneas',NULL,'Avena','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Centeno','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Cebada','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Trigo','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Festuca','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Rye Grass Anual','kg',NULL,NULL,NULL),
  ('Semillas','Gramíneas',NULL,'Rye Grass Perenne','kg',NULL,NULL,NULL),
  ('Semillas','Leguminosas',NULL,'Vicia Villosa','kg',NULL,NULL,NULL),
  ('Semillas','Leguminosas',NULL,'Melilotus','kg',NULL,NULL,NULL),
  ('Semillas','Leguminosas',NULL,'Trébol Blanco','kg',NULL,NULL,NULL),
  ('Semillas','Leguminosas',NULL,'Trébol Rojo','kg',NULL,NULL,NULL),
  ('Semillas','Leguminosas',NULL,'Alfalfa','kg',NULL,NULL,NULL),
  ('Semillas','Crucíferas',NULL,'Mostaza Blanca','kg',NULL,NULL,NULL),
  ('Semillas','Crucíferas',NULL,'Rabanito Forrajero','kg',NULL,NULL,NULL),
  ('Semillas','Mezclas',NULL,'Mezcla para Cobertura','kg',NULL,NULL,NULL),
  -- 8. Enmiendas
  ('Enmiendas',NULL,NULL,'Yeso Agrícola','kg',NULL,NULL,NULL),
  ('Enmiendas',NULL,NULL,'Cal Agrícola','kg',NULL,NULL,NULL),
  ('Enmiendas',NULL,NULL,'Dolomita','kg',NULL,NULL,NULL),
  ('Enmiendas',NULL,NULL,'Carbonato de Calcio','kg',NULL,NULL,NULL),
  ('Enmiendas',NULL,NULL,'Azufre Elemental','kg',NULL,NULL,NULL),
  ('Enmiendas',NULL,NULL,'Zeolita','kg',NULL,NULL,NULL),
  -- 9. Material Vegetal
  ('Material Vegetal',NULL,NULL,'Plantín de Vid','unidad',NULL,NULL,NULL),
  ('Material Vegetal',NULL,NULL,'Barbado','unidad',NULL,NULL,NULL),
  ('Material Vegetal',NULL,NULL,'Estaca','unidad',NULL,NULL,NULL),
  ('Material Vegetal',NULL,NULL,'Portainjerto','unidad',NULL,NULL,NULL),
  ('Material Vegetal',NULL,NULL,'Yema para Injerto','unidad',NULL,NULL,NULL),
  -- 10. Alambrado y Conducción
  ('Alambrado y Conducción',NULL,NULL,'Alambre Galvanizado Nº 8','kg',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Alambre Galvanizado Nº 10','kg',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Alambre Alta Resistencia','kg',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Grapas','unidad',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Tensores','unidad',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Anclas','unidad',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Tutor de Madera','unidad',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Tutor Metálico','unidad',NULL,NULL,NULL),
  ('Alambrado y Conducción',NULL,NULL,'Tutor PVC','unidad',NULL,NULL,NULL),
  -- 11. Insumos para Poda, Atadura e Injertos
  ('Poda, Atadura e Injertos',NULL,NULL,'Hilo para Atadora','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Cinta Biodegradable','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Rafia','kg',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Clips para Atado','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Cinta para Injertos','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Parafina para Injertos','kg',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Pasta Cicatrizante','kg',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Hormona Enraizante','L',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Sellador de Poda','kg',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Lubricante para Tijeras','L',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Piedra de Afilar','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Repuestos para Tijeras','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Cadena para Motosierra','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Lima para Cadena','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Hilo de Nylon para Desmalezadora','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Disco para Desmalezadora','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Disco de Corte','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Piolín de Replanteo','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Estacas de Marcación','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Pintura para Marcación','aerosol',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Cinta de Señalización','rollo',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Bolsas para Residuos','unidad',NULL,NULL,NULL),
  ('Poda, Atadura e Injertos',NULL,NULL,'Precintos Plásticos','unidad',NULL,NULL,NULL),
  -- 12. Insumos de Riego
  ('Insumos de Riego',NULL,NULL,'Gotero','unidad',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Microaspersor','unidad',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Cinta de Riego','metro',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Manguera PE','metro',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Válvula','unidad',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Filtro','unidad',NULL,NULL,NULL),
  ('Insumos de Riego',NULL,NULL,'Fertilizante Soluble','kg',NULL,NULL,NULL),
  -- 13. Combustibles y Lubricantes
  ('Combustibles y Lubricantes','Combustible',NULL,'Gasoil','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'Nafta Súper','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'Nafta Premium','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'GLP','kg',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'Leña','kg',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'Briquetas','kg',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Combustible',NULL,'Velas Antiheladas','unidad',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Lubricante',NULL,'Aceite Motor','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Lubricante',NULL,'Aceite Hidráulico','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Lubricante',NULL,'Grasa','kg',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Lubricante',NULL,'Refrigerante','L',NULL,NULL,NULL),
  ('Combustibles y Lubricantes','Lubricante',NULL,'Líquido de Frenos','L',NULL,NULL,NULL),
  -- 14. Limpieza y Desinfección
  ('Limpieza y Desinfección',NULL,NULL,'Alcohol','L',NULL,NULL,NULL),
  ('Limpieza y Desinfección',NULL,NULL,'Hipoclorito de Sodio','L',NULL,NULL,NULL),
  ('Limpieza y Desinfección',NULL,NULL,'Detergente Industrial','L',NULL,NULL,NULL),
  ('Limpieza y Desinfección',NULL,NULL,'Desengrasante','L',NULL,NULL,NULL),
  ('Limpieza y Desinfección',NULL,NULL,'Jabón Líquido','L',NULL,NULL,NULL),
  -- 15. EPP
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Casco','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Guantes','par',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Antiparras','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Protector Auditivo','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Barbijo','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Máscara con Filtros','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Arnés','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Botas de Seguridad','par',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Traje Impermeable','unidad',NULL,NULL,NULL),
  ('Elementos de Protección Personal (EPP)',NULL,NULL,'Chaleco Reflectivo','unidad',NULL,NULL,NULL)
) AS v(cat,fam,pa,nom,uni,dmin,dmax,ud)
ON CONFLICT ("ambito","categoria","nombre_comercial") DO NOTHING;

-- ══════════════════════════ BODEGA ══════════════════════════
INSERT INTO "insumo_maestro"
  ("ambito","categoria","familia","principio_activo","nombre_comercial","unidad","dosis_min","dosis_max","unidad_dosis")
SELECT 'bodega'::"AmbitoInsumo", v.cat, v.fam, v.pa, v.nom, v.uni, v.dmin::numeric, v.dmax::numeric, v.ud
FROM (VALUES
  -- 1. Levaduras
  ('Levaduras','Seca Activa',NULL,'Saccharomyces cerevisiae','kg',NULL,NULL,NULL),
  ('Levaduras','Seca Activa',NULL,'Saccharomyces bayanus','kg',NULL,NULL,NULL),
  ('Levaduras','Seca Activa',NULL,'Levadura para Blancos','kg',NULL,NULL,NULL),
  ('Levaduras','Seca Activa',NULL,'Levadura para Tintos','kg',NULL,NULL,NULL),
  ('Levaduras','Seca Activa',NULL,'Levadura para Espumantes','kg',NULL,NULL,NULL),
  -- 2. Nutrientes y Activadores de Fermentación
  ('Nutrientes y Activadores','Nitrogenados',NULL,'DAP','kg',NULL,NULL,NULL),
  ('Nutrientes y Activadores','Orgánicos',NULL,'Nutriente Complejo','kg',NULL,NULL,NULL),
  ('Nutrientes y Activadores','Activadores',NULL,'Activador de Fermentación','kg',NULL,NULL,NULL),
  ('Nutrientes y Activadores','Inactivados',NULL,'Levaduras Inactivadas','kg',NULL,NULL,NULL),
  ('Nutrientes y Activadores','Vitaminas',NULL,'Tiamina','kg',NULL,NULL,NULL),
  -- 3. Enzimas Enológicas
  ('Enzimas Enológicas','Pectolíticas',NULL,'Pectinasa','kg',NULL,NULL,NULL),
  ('Enzimas Enológicas','Maceración',NULL,'Enzima Maceración','kg',NULL,NULL,NULL),
  ('Enzimas Enológicas','Clarificación',NULL,'Enzima Clarificante','kg',NULL,NULL,NULL),
  ('Enzimas Enológicas','Aromáticas',NULL,'Enzima Aromática','kg',NULL,NULL,NULL),
  -- 4. Correctores de Acidez
  ('Correctores de Acidez','Ácido',NULL,'Ácido Tartárico','kg',NULL,NULL,NULL),
  ('Correctores de Acidez','Ácido',NULL,'Ácido Cítrico','kg',NULL,NULL,NULL),
  ('Correctores de Acidez','Ácido',NULL,'Ácido Málico','kg',NULL,NULL,NULL),
  ('Correctores de Acidez','Alcalinizante',NULL,'Carbonato de Calcio','kg',NULL,NULL,NULL),
  ('Correctores de Acidez','Alcalinizante',NULL,'Bicarbonato de Potasio','kg',NULL,NULL,NULL),
  -- 5. Clarificantes
  ('Clarificantes','Mineral',NULL,'Bentonita Sódica','kg',NULL,NULL,NULL),
  ('Clarificantes','Mineral',NULL,'Bentonita Cálcica','kg',NULL,NULL,NULL),
  ('Clarificantes','Proteico',NULL,'Gelatina','kg',NULL,NULL,NULL),
  ('Clarificantes','Proteico',NULL,'Albúmina','kg',NULL,NULL,NULL),
  ('Clarificantes','Proteico',NULL,'Caseína','kg',NULL,NULL,NULL),
  ('Clarificantes','Vegetal',NULL,'Proteína Vegetal','kg',NULL,NULL,NULL),
  ('Clarificantes','Mineral',NULL,'Sílice Coloidal','L',NULL,NULL,NULL),
  -- 6. Taninos Enológicos
  ('Taninos Enológicos','Roble',NULL,'Tanino Elágico','kg',NULL,NULL,NULL),
  ('Taninos Enológicos','Quebracho',NULL,'Tanino Condensado','kg',NULL,NULL,NULL),
  ('Taninos Enológicos','Semilla',NULL,'Tanino de Semilla','kg',NULL,NULL,NULL),
  ('Taninos Enológicos','Hollejo',NULL,'Tanino de Hollejo','kg',NULL,NULL,NULL),
  -- 7. Estabilizantes
  ('Estabilizantes','Tartárica',NULL,'CMC','kg',NULL,NULL,NULL),
  ('Estabilizantes','Tartárica',NULL,'Ácido Metatartárico','kg',NULL,NULL,NULL),
  ('Estabilizantes','Coloidal',NULL,'Goma Arábiga','L',NULL,NULL,NULL),
  -- 8. Conservantes
  ('Conservantes','Sulfitos',NULL,'Metabisulfito de Potasio','kg',NULL,NULL,NULL),
  ('Conservantes','Sulfitos',NULL,'Anhídrido Sulfuroso','kg',NULL,NULL,NULL),
  ('Conservantes','Antioxidante',NULL,'Ácido Ascórbico','kg',NULL,NULL,NULL),
  ('Conservantes','Antimicrobiano',NULL,'DMDC','L',NULL,NULL,NULL),
  -- 9. Gases Enológicos
  ('Gases Enológicos','Oxígeno Alimenticio',NULL,'Oxígeno','m³',NULL,NULL,NULL),
  ('Gases Enológicos','Nitrógeno Alimenticio',NULL,'Nitrógeno','m³',NULL,NULL,NULL),
  ('Gases Enológicos','CO₂ Alimenticio',NULL,'Dióxido de Carbono','kg',NULL,NULL,NULL),
  ('Gases Enológicos','Argón',NULL,'Argón','m³',NULL,NULL,NULL),
  -- 10. Productos de Limpieza y Sanitización (CIP)
  ('Limpieza y Sanitización (CIP)','Alcalino',NULL,'Soda Cáustica','kg',NULL,NULL,NULL),
  ('Limpieza y Sanitización (CIP)','Ácido',NULL,'Ácido Nítrico','L',NULL,NULL,NULL),
  ('Limpieza y Sanitización (CIP)','Ácido',NULL,'Ácido Fosfórico','L',NULL,NULL,NULL),
  ('Limpieza y Sanitización (CIP)','Desinfectante',NULL,'Ácido Peracético','L',NULL,NULL,NULL),
  ('Limpieza y Sanitización (CIP)','Desinfectante',NULL,'Hipoclorito de Sodio','L',NULL,NULL,NULL),
  ('Limpieza y Sanitización (CIP)','Detergente',NULL,'Detergente CIP','L',NULL,NULL,NULL),
  -- 11. Botellas
  ('Botellas','Bordelesa',NULL,'Bordelesa 750 ml','unidad',NULL,NULL,NULL),
  ('Botellas','Borgoña',NULL,'Borgoña 750 ml','unidad',NULL,NULL,NULL),
  ('Botellas','Alta Gama',NULL,'Alta Gama 750 ml','unidad',NULL,NULL,NULL),
  ('Botellas','Media Botella',NULL,'Media Botella 375 ml','unidad',NULL,NULL,NULL),
  ('Botellas','Magnum',NULL,'Magnum 1500 ml','unidad',NULL,NULL,NULL),
  -- 12. Cierres
  ('Cierres','Corcho Natural',NULL,'Corcho Natural Premium','unidad',NULL,NULL,NULL),
  ('Cierres','Corcho Aglomerado',NULL,'Corcho Aglomerado Estándar','unidad',NULL,NULL,NULL),
  ('Cierres','Corcho Técnico',NULL,'Corcho Microaglomerado','unidad',NULL,NULL,NULL),
  ('Cierres','Tapa Rosca',NULL,'Tapa Rosca Stelvin','unidad',NULL,NULL,NULL),
  ('Cierres','Tapón Sintético',NULL,'Tapón Sintético','unidad',NULL,NULL,NULL),
  -- 13. Cápsulas
  ('Cápsulas','PVC',NULL,'Cápsula PVC','unidad',NULL,NULL,NULL),
  ('Cápsulas','Estaño',NULL,'Cápsula Estaño','unidad',NULL,NULL,NULL),
  ('Cápsulas','Polilaminada',NULL,'Cápsula Polilaminada','unidad',NULL,NULL,NULL),
  -- 14. Etiquetas
  ('Etiquetas','Frontal',NULL,'Etiqueta Principal','unidad',NULL,NULL,NULL),
  ('Etiquetas','Contraetiqueta',NULL,'Contraetiqueta','unidad',NULL,NULL,NULL),
  ('Etiquetas','Collarín',NULL,'Collarín','unidad',NULL,NULL,NULL),
  ('Etiquetas','Medalla',NULL,'Medalla Promocional','unidad',NULL,NULL,NULL),
  -- 15. Embalajes
  ('Embalajes','Caja Cartón',NULL,'Caja x 6','unidad',NULL,NULL,NULL),
  ('Embalajes','Caja Cartón',NULL,'Caja x 12','unidad',NULL,NULL,NULL),
  ('Embalajes','Separador',NULL,'Cartón Corrugado','unidad',NULL,NULL,NULL),
  ('Embalajes','Divisor',NULL,'Divisor Cartón','unidad',NULL,NULL,NULL),
  -- 16. Materiales de Paletizado
  ('Paletizado','Pallet',NULL,'Pallet Madera','unidad',NULL,NULL,NULL),
  ('Paletizado','Film',NULL,'Film Stretch','kg',NULL,NULL,NULL),
  ('Paletizado','Esquinero',NULL,'Esquinero Cartón','unidad',NULL,NULL,NULL),
  ('Paletizado','Fleje',NULL,'Fleje Polipropileno','metro',NULL,NULL,NULL),
  ('Paletizado','Hebilla',NULL,'Hebilla Fleje','unidad',NULL,NULL,NULL),
  -- 17. Insumos de Despacho
  ('Insumos de Despacho','Precinto',NULL,'Precinto Seguridad','unidad',NULL,NULL,NULL),
  ('Insumos de Despacho','Cinta',NULL,'Cinta Embalaje','rollo',NULL,NULL,NULL),
  ('Insumos de Despacho','Etiqueta Logística',NULL,'Etiqueta Código Barras','unidad',NULL,NULL,NULL),
  ('Insumos de Despacho','Etiqueta QR',NULL,'Etiqueta QR','unidad',NULL,NULL,NULL),
  -- 18. Insumos de Laboratorio
  ('Insumos de Laboratorio','Reactivos',NULL,'Reactivos Analíticos','frasco',NULL,NULL,NULL),
  ('Insumos de Laboratorio','Material',NULL,'Papel Filtro','unidad',NULL,NULL,NULL),
  ('Insumos de Laboratorio','Material',NULL,'Tubos de Ensayo','unidad',NULL,NULL,NULL),
  ('Insumos de Laboratorio','Material',NULL,'Pipetas Desechables','unidad',NULL,NULL,NULL),
  ('Insumos de Laboratorio','Material',NULL,'Guantes Nitrilo','caja',NULL,NULL,NULL)
) AS v(cat,fam,pa,nom,uni,dmin,dmax,ud)
ON CONFLICT ("ambito","categoria","nombre_comercial") DO NOTHING;
